--
-- Table structure for table `nigerian_local_government_areas`
--

CREATE TABLE `nigerian_local_government_areas` (
  `id` int(100) NOT NULL,
  `name` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `nigerian_local_government_areas`
--

INSERT INTO `nigerian_local_government_areas` (`name`) VALUES
('Afijio'),
('Akinyele'),
('Atiba'),
('Atigbo'),
('Egbeda'),
('Ibadan Central'),
('Ibadan North'),
('Ibadan North West '),
('Ibadan South East'),
('Ibadan South West '),
('Ibarapa Central '),
('Ibarapa East '),
('Ibarapa North'),
('Ido'),
('Irepo'),
('Iseyin'),
('Itesiwaju'),
('Iwajowa'),
('Kajola'),
('Lagelu Ogbomosho North '),
('Ogbmosho South '),
('Ogo Oluwa '),
('Olorunsogo'),
('Oluyole'),
('Ona-Ara'),
('Orelope'),
('Ori Ire '),
('Oyo East'),
('Oyo West '),
('Saki East '),
('Saki West '),
('Surulere'),
('Adavi'),
('Ajaokuta'),
('Ankpa'),
('Bassa'),
('Dekina'),
('Ibaji'),
('Idah'),
('Igalamela-Odolu'),
('Ijumu'),
('Kabba/Bunu '),
('Kogi'),
('Lokoja'),
('Mopa-Muro '),
('Ofu'),
('Ogori/Mangongo '),
('Okehi'),
('Okene'),
('Olamabolo'),
('Omala'),
('Yagba East '),
('Yagba West'),
('Agaie'),
('Agwara'),
('Bida'),
('Borgu'),
('Bosso'),
('Chanchaga'),
('Edati'),
('Gbako'),
('Gurara'),
('Katcha'),
('Kontagora'),
('Lapai'),
('Lavun'),
('Magama'),
('Mariga'),
('Mashegu'),
('Mokwa'),
('Muya'),
('Pailoro'),
('Rafi'),
('Rijau'),
('Shiroro'),
('Suleja'),
('Tafa'),
('Wushishi'),
('Auyo'),
('Babura'),
('Birni Kudu'),
('Biriniwa'),
('Buji'),
('Dutse'),
('Gagarawa'),
('Garki'),
('Gumel'),
('Guri'),
('Gwaram'),
('Gwiwa'),
('Hadejia'),
('Jahun'),
('Kafin Hausa '),
('Kaugama Kazaure '),
('Kiri Kasamma '),
('Kiyawa'),
('Maigatari'),
('Malam Madori '),
('Miga'),
('Ringim'),
('Roni '),
('Sule-Tankarkar '),
('Taura  '),
('Yankwashi'),
('Gwagwalada'),
('Kuje'),
('Abaji'),
('Abuja Municipal'),
('Bwari'),
('Kwali'),
('Dambatta'),
('Fagge'),
('Nasarawa'),
('Kano Municipal'),
('Tarauni'),
('Dala'),
('Rogo'),
('Bichi'),
('Shanono'),
('Kura'),
('Tofa'),
('Bebeji'),
('Bagwai'),
('Bunkure'),
('Chikun'),
('Giwa'),
('Igabi'),
('Ikara'),
('Jaba'),
('Jema\'a'),
('Kachia'),
('Kaduna North'),
('Kaduna South '),
('Kagarko'),
('Kajuru'),
('Kaura'),
('Kauru'),
('Kubau'),
('Kudan'),
('Lere'),
('Makarfi'),
('Sabon-Gari '),
('Sanga'),
('Soba'),
('Zango-Kataf '),
('Zaria'),
('Binji'),
('Bodinga'),
('Dange-shnsi '),
('Gada'),
('Goronyo'),
('Gudu'),
('Gawabawa'),
('Illela'),
('Isa'),
('Kware'),
('Kebbe'),
('Rabah'),
('Sabon birni '),
('Shagari'),
('Silame'),
('Sokoto North'),
('Sokoto South'),
('Tambuwal'),
('Tureta'),
('Wamako'),
('Wurno'),
('Yabo');

--
-- Indexes for table `nigerian_local_government_areas`
--
ALTER TABLE `nigerian_local_government_areas`
  ADD PRIMARY KEY (`id`),
  ADD KEY `nigerian_state` (`nigerian_state`);

--
-- AUTO_INCREMENT for table `nigerian_local_government_areas`
--
ALTER TABLE `nigerian_local_government_areas`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=169;
--
